CRUD_example/config/routes.rb
Rails.application.routes.draw do

  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'controller#action'
  root 'pages#index'



  resources :posts #(creat routes for post)


  # classic declaration
  #get '/posts', to: 'posts#index'
  #get '/posts/:id', to: 'posts#show', as:'post'

end

CRUD_example/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

CRUD_example/app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true


end

CRUD_example/app/models/post.rb
class Post < ApplicationRecord

  belongs_to :category

  #include PostValidation
  validates :name, presence: true
  validates :category_id, presence: true

end

CRUD_example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

CRUD_example/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

CRUD_example/app/controllers/pages_controller.rb
class PagesController < ActionController::Base

  #protect_from_forgery with: :exception

  def index
  end


end

CRUD_example/app/controllers/posts_controller.rb
class PostsController < ApplicationController


  #Usefull to avoid code duplication
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  private

  def set_post
    @post = Post.find(params[:id])
  end



  public

  def index
    @posts = Post.includes(:category).all
  end

  def show
    #@post = Post.find(params[:id])
  end

  def edit
    #@post = Post.find(params[:id])
    @categories = Category.all
  end

  def update
    #@post = Post.find(params[:id])
    params.inspect
    if @post.update(params.require(:post).permit(:name, :content, :category_id))
      redirect_to posts_url, notice: 'The article has been edited succesully :) '
    else
      render :edit
    end
  end


  def create
    #@post = Post.find(params[:id])
    @post = Post.new
    params.inspect
    if @post.update(params.require(:post).permit(:name, :content, :category_id))
      redirect_to posts_url, notice: 'The article has been added succesully :) '
    else
      render :new
    end
  end


  def destroy
    #@post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_url, notice: 'The article has been deleted succesully :) '
  end


  def new
    @post = Post.new
  end



end

CRUD_example/app/helpers/application_helper.rb
module ApplicationHelper
end

CRUD_example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


</head>

<body>
  <%= yield %>
</body>
</html>

CRUD_example/app/views/pages/index.html.erb
<h1>Hello world !!!</h1>

CRUD_example/app/views/posts/_form.html.erb
<%= simple_form_for post do |f| %>
  <%= f.input :name %>
  <%= f.input :content %>
  <%= f.input :category_id, collection: @categories %>
  <%= f.button :submit, post.new_record? ? 'Create' : 'Edit' %> <!-- If its a creation 'Create' is written-->
<% end %>

CRUD_example/app/views/posts/edit.html.erb
<h1>Edit article </h1>


<!-- call the form from form.html.erb -->
<%= render 'form', post: @post %>

CRUD_example/app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<% if flash[:notice] %>
<div class="alert alert-success">
  <%= flash[:notice] %>
</div>
<% end %>

<ul>
  <% @posts.each do |post|  %>
  <% if post.category %>
  <li> <a href="/posts/<%=post.id%>"><%= post.name+ ', category:  '+ post.category.name %></a>  : <%=  post.content %></li>
  <% else %>
  <li> <a href="<%= post_path(post.id)%>"> <%= post.name %></a>  : <%=  post.content %></li>
  <% end %>

  <li> <a href="<%= url_for(controller:'posts', action:'show', id: post.id)%>"> <%= post.name %></a>  : <%=  post.content %></li>
  <li>
    <%= link_to post.name, post_path(post) %>
    <%= link_to("Edit", [:edit, post]) %> <!-- call edit on post: [action, entity] -->
    <%= link_to("Delete", post, method: :delete, data: {confirm: "Are You Sure ?"}) %> <!-- usefull by using Jquery UJS-->
  </li>
  <% end %>
</ul>


<%= link_to "New", new_post_path %>


<p><%= posts_path %> </p>

CRUD_example/app/views/posts/new.html.erb
<h1>New Article </h1>



<!-- call the form from form.html.erb -->
<%= render 'form', post: @post %>

CRUD_example/app/views/posts/show.html.erb
<h1><%= @post.name %></h1>


<p><%= @post.content %><p>


<p><%= time_ago_in_words(@post.created_at) %> ago</p>


<!--  link_to(name, link)  -->
<p> <%= link_to('Back', posts_path) %></p>